apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap14-gitpyart-test
  janus-idp.io/tekton: rhtap14-gitpyart-test
  backstage.io/kubernetes-id: rhtap14-gitpyart-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap14-gitpyart-test
resources:
- deployment.yaml
- route.yaml
- service.yaml
